var hamburger_1 = new Hamburger(Hamburger.SIZE_LARGE, Hamburger.STUFFING_CHEESE);
var hamburger_2 = new Hamburger(Hamburger.SIZE_SMALL, Hamburger.STUFFING_SALAD);
var caesar = new Salad(Salad.CAESAR, 200);
var cola = new Drink(Drink.COLA);

var order1 = new Order(hamburger_2, caesar, cola);
order1.getItems();
order1.calculateTotalCalories();
order1.calculateTotalPrice();
order1.addPosition(hamburger_1);
order1.getItems();
order1.calculateTotalCalories();
order1.calculateTotalPrice();
order1.deletePosition(hamburger_2);
order1.getItems();
order1.calculateTotalCalories();
order1.calculateTotalPrice();
order1.payForTheOrder();
order1.addPosition(hamburger_1);

var order2 = new Order();
order2.getItems();
order2.calculateTotalCalories();
order2.calculateTotalPrice();
order2.addPosition(hamburger_1);
order2.addPosition(cola);
order2.getItems();
order2.calculateTotalCalories();
order2.calculateTotalPrice();
order2.payForTheOrder();
